server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(wOGKNtONvFrN1/MGp5wB55c1NL4qT/Q8nUnVS7iD2MXcqoEdlokULPJLhMYX/WRijwUSHVYOAhM=)
    username: ENC(kMLuw+dIjrtU5eqav0S8jHe/RbpOyOz+)
    password: ENC(Fzk9bplkszsXVGOdHsEd6cCG3Y0JjxDE3Iv7UYc5YIE=)
  data:
    redis:
      host: ENC(rGpJg8Rb4q4xDVfXbxdzgVmbUIXwcVPv)
      port: 6379
      password: ENC(CpXUjKBJ8yiRNSFwb2QaIW2+CtLtQ8VU)
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${JOB_NAME:NONE}

## AWS 용량때문에 로그 찍지 않도록 설정함.
#logging:
#  level:
#    root: INFO
#  file:
#    name: /appstore/batch/practice/logs/StudySpringBatch.log  # 로그 파일 경로 지정
#    pattern:
#      console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"  # 콘솔 로그 패턴 설정
#      file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"  # 파일 로그 패턴 설정
#  rollingpolicy:
#    filenamepattern: /appstore/batch/practice/logs/ogfile-%d{yyyy-MM-dd}-%i.log.zip
#    maxfilesize: 10MB
#    maxhistory: 7
#    totalcap: 100MB
#    compressionmode: ON

redis:
  key:
    transaction: TRANSACTION

backend:
  ip: 127.0.0.1
  port: 8081

study:
  enabledschedule: ${spring.enabledschedule:false}
  cron:
    concurrencyJob: "*/1 * * * * *"